{{- if .Values.configMap.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "anythingllm.fullname" . }}
  labels:
    {{- include "anythingllm.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.env }}
  {{- if and (ne $key "JWT_SECRET") $val }}
  {{ $key }}: "{{ $val }}"
  {{- end }}
  {{- end }}
{{- end }}
