{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "anythingllm.fullname" . }}
  labels:
    {{- include "anythingllm.labels" . | nindent 4 }}
{{- end }}
