{{- if and (not .Values.existingSecret) (include "proxy.hasSecretEnv" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "proxy.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "proxy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.secretEnv }}
  {{ $key }}: "{{ $val }}"
  {{- end }}
{{- end }}
